// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoLearning.Web.Admin.VideoIndexer.Operations
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;

    /// <summary>
    /// The Operations API contains all the Video Indexer APIs, such as Upload
    /// video, Get insights, and other operations
    /// </summary>
    public partial interface IOperationsClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


            /// <summary>
        /// Get Accounts
        /// </summary>
        /// Get Accounts
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (User Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='generateAccessTokens'>
        /// Whether to generate an access token for each account. Possible
        /// values include: 'true', 'false'
        /// </param>
        /// <param name='allowEdit'>
        /// Whether the tokens have write permissions. Possible values
        /// include: 'true', 'false'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetAccountsWithHttpMessagesAsync(string location, string accessToken, string generateAccessTokens = default(string), string allowEdit = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Account
        /// </summary>
        /// Get Account Details
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='includeUsage'>
        /// Whether to retrieve the usage information for the account.
        /// Possible values include: 'true', 'false'
        /// </param>
        /// <param name='includeAmsInfo'>
        /// Whether to retrieve the Azure Media Services instance information.
        /// Possible values include: 'true', 'false'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetAccountWithHttpMessagesAsync(string location, string accountId, string accessToken, string includeUsage = default(string), string includeAmsInfo = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Video Index
        /// </summary>
        /// Get Video Index
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos&lt;br&gt;
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='language'>
        /// The language of the captions.
        /// Supported languages: Afrikaans: Af-ZA, Arabic: ar-EG, Bangla:
        /// Bn-BD, Bosnian: Bs-Latn, Bulgarian: Bg-BG, Catalan: Ca-ES,
        /// Chinese (Simplified): zh-Hans, Chinese (Traditional): Zh-Hant,
        /// Croatian: Hr-HR, Czech: Cs-CZ, Danish: Da-DK, Dutch: Nl-NL,
        /// English: en-US, Estonian: Et-EE, Fijian: En-FJ, Filipino: fil-PH,
        /// Finnish: Fi-FI, French: fr-FR, German: de-DE, Greek: El-GR,
        /// Haitian: Fr-HT, Hebrew: He-IL, Hindi: Hi-IN, Hungarian: Hu-HU,
        /// Indonesian: Id-ID, Italian: it-IT, Japanese: ja-JP, Kiswahili:
        /// Sw-KE, Korean: Ko-KR, Latvian: Lv-LV, Lithuanian: Lt-LT,
        /// Malagasy: Mg-MG, Malay: Ms-MY, Maltese: Mt-MT, Norwegian: Nb-NO,
        /// Persian: Fa-IR, Polish: Pl-PL, Portuguese: pt-BR, Romanian:
        /// Ro-RO, Russian: ru-RU, Samoan: En-WS, Serbian (Cyrillic):
        /// Sr-Cyrl-RS, Serbian (Latin): Sr-Latn-RS, Slovak: Sk-SK,
        /// Slovenian: Sl-SI, Spanish: es-ES, Swedish: Sv-SE, Tamil: Ta-IN,
        /// Thai: Th-TH, Tongan: To-TO, Turkish: Tr-TR, Ukrainian: Uk-UA,
        /// Urdu: Ur-PK, Vietnamese: Vi-VN. Possible values include:
        /// 'English', 'Spanish', 'Russian', 'Japanese', 'German', 'French',
        /// 'Portuguese', 'Italian', 'Chinese', 'Filipino', 'Arabic',
        /// 'ar-EG', 'en-US', 'es-ES', 'fr-FR', 'de-DE', 'it-IT', 'ja-JP',
        /// 'pt-BR', 'ru-RU', 'zh-Hans', 'fil-PH', 'Af-ZA', 'Bn-BD',
        /// 'Bs-Latn', 'Bg-BG', 'Ca-ES', 'Hr-HR', 'Cs-CZ', 'Da-DK', 'Nl-NL',
        /// 'En-FJ', 'En-GB', 'En-WS', 'Es-MX', 'Et-EE', 'Fi-FI', 'El-GR',
        /// 'Fr-HT', 'He-IL', 'Hi-IN', 'Hu-HU', 'Id-ID', 'Sw-KE', 'Ko-KR',
        /// 'Lv-LV', 'Lt-LT', 'Mg-MG', 'Ms-MY', 'Mt-MT', 'Nb-NO', 'Fa-IR',
        /// 'Pl-PL', 'Ro-RO', 'Sr-Cyrl-RS', 'Sr-Latn-RS', 'Sk-SK', 'Sl-SI',
        /// 'Sv-SE', 'Ta-IN', 'Th-TH', 'To-TO', 'Tr-TR', 'Uk-UA', 'Ur-PK',
        /// 'Vi-VN', 'Zh-Hant'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetVideoIndexWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken = default(string), string language = "English", Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List Videos
        /// </summary>
        /// Get a list of videos in the account
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='pageSize'>
        /// page size
        /// </param>
        /// <param name='skip'>
        /// The number of pages to skip
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ListVideosWithHttpMessagesAsync(string location, string accountId, string accessToken, int? pageSize = default(int?), int? skip = default(int?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Upload Video
        /// </summary>
        /// Uploads the given video, starts indexing it and returns a new
        /// Video id.&lt;br&gt;
        /// The supported formats are listed
        /// &lt;a
        /// href=https://docs.microsoft.com/en-us/azure/media-services/media-services-media-encoder-standard-formats
        /// target="_blank"&gt; here&lt;/a&gt;
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account or Video with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='name'>
        /// The video name
        /// </param>
        /// <param name='description'>
        /// The video description.
        /// </param>
        /// <param name='partition'>
        /// A partition to partition videos by (used for searching a specific
        /// partition)
        /// </param>
        /// <param name='externalId'>
        /// An external id to associate with the video (can be searched for
        /// later).
        /// </param>
        /// <param name='callbackUrl'>
        /// A url to notify when indexing is completed.
        /// It should be a POST url and VideoIndexer will add 2 additional
        /// query string parameters to it: id and state.
        /// 
        /// For example, if the callback url is
        /// 'https://test.com/notifyme?projectName=MyProject', the
        /// notification will be sent with additional parameters to
        /// 'https://test.com/notifyme?projectName=MyProject&amp;id=1234abcd&amp;state=Processed'.
        /// </param>
        /// <param name='metadata'>
        /// Metadata to associate with the video (will be returned in queries).
        /// </param>
        /// <param name='language'>
        /// The language of the video, to be used when generating the
        /// transcript. Arabic: ar-EG, Chinese (Simplified): zh-Hans,
        /// English: en-US, French: fr-FR, German: de-DE, Italian: it-IT,
        /// Japanese: ja-JP, Portuguese: pt-BR, Russian: ru-RU, Spanish:
        /// es-ES, Korean: ko-KR, Hindi: hi-IN or auto for auto-detection.
        /// Possible values include: 'English', 'Spanish', 'Russian',
        /// 'Japanese', 'German', 'French', 'Portuguese', 'Italian',
        /// 'Chinese', 'Filipino', 'Arabic', 'ar-EG', 'en-US', 'es-ES',
        /// 'fr-FR', 'de-DE', 'it-IT', 'ja-JP', 'pt-BR', 'ru-RU', 'zh-Hans',
        /// 'fil-PH', 'Af-ZA', 'Bn-BD', 'Bs-Latn', 'Bg-BG', 'Ca-ES', 'Hr-HR',
        /// 'Cs-CZ', 'Da-DK', 'Nl-NL', 'En-FJ', 'En-GB', 'En-WS', 'Es-MX',
        /// 'Et-EE', 'Fi-FI', 'El-GR', 'Fr-HT', 'He-IL', 'Hi-IN', 'Hu-HU',
        /// 'Id-ID', 'Sw-KE', 'Ko-KR', 'Lv-LV', 'Lt-LT', 'Mg-MG', 'Ms-MY',
        /// 'Mt-MT', 'Nb-NO', 'Fa-IR', 'Pl-PL', 'Ro-RO', 'Sr-Cyrl-RS',
        /// 'Sr-Latn-RS', 'Sk-SK', 'Sl-SI', 'Sv-SE', 'Ta-IN', 'Th-TH',
        /// 'To-TO', 'Tr-TR', 'Uk-UA', 'Ur-PK', 'Vi-VN', 'Zh-Hant', 'auto'
        /// </param>
        /// <param name='videoUrl'>
        /// A public url of the video/audio file (url encoded). If not
        /// specified, the file should be passed as a multipart/form body
        /// content.
        /// </param>
        /// <param name='fileName'>
        /// The uploaded file name.
        /// </param>
        /// <param name='indexingPreset'>
        /// The indexing preset to use
        /// (Default/AudioOnly/VideoOnly/DefaultWithNoiseReduction). Possible
        /// values include: 'Default', 'AudioOnly', 'VideoOnly',
        /// 'DefaultWithNoiseReduction'
        /// </param>
        /// <param name='streamingPreset'>
        /// The streaming preset to use
        /// (Default/SingleBitrate/AdaptiveBitrate/NoStreaming). Possible
        /// values include: 'Default', 'AdaptiveBitrate', 'NoStreaming',
        /// 'SingleBitrate'
        /// </param>
        /// <param name='linguisticModelId'>
        /// Linguistic model id as received by 'create linguistic model' call
        /// </param>
        /// <param name='privacy'>
        /// The video privacy (Private or Public). Possible values include:
        /// 'Private', 'Public'
        /// </param>
        /// <param name='externalUrl'>
        /// An external URL to associate with the video (can be retrieved
        /// later)
        /// </param>
        /// <param name='assetId'>
        /// Azure media services asset id. Used to index from existing assets
        /// in your connected Azure media services account. (Paid only)
        /// </param>
        /// <param name='priority'>
        /// Index priority (Low, Normal and High). Can be used in paid regions
        /// only. Possible values include: 'Low', 'Normal', 'High'
        /// </param>
        /// <param name='personModelId'>
        /// Faces will be identified against the provided person model.
        /// </param>
        /// <param name='brandsCategories'>
        /// List of brands categories delimited by comma. Video indexer will
        /// only take these categories in to account when indexing. If not
        /// specified all brands will be used.
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UploadVideoWithHttpMessagesAsync(string location, string accountId, string accessToken, string name, string description = default(string), string partition = default(string), string externalId = default(string), string callbackUrl = default(string), string metadata = default(string), string language = default(string), string videoUrl = default(string), string fileName = default(string), string indexingPreset = default(string), string streamingPreset = "Default", string linguisticModelId = default(string), string privacy = default(string), string externalUrl = default(string), string assetId = default(string), string priority = default(string), string personModelId = default(string), string brandsCategories = default(string), object body = default(object), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Search Videos
        /// </summary>
        /// Search videos in the specified account
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='query'>
        /// Free text to search for.
        /// </param>
        /// <param name='textScope'>
        /// The text scope to search in. Possible values include:
        /// 'Transcript', 'Ocr'
        /// </param>
        /// <param name='privacy'>
        /// A privacy level (Private, Organization, Public). Possible values
        /// include: 'Private', 'Public'
        /// </param>
        /// <param name='id'>
        /// A breakdown id to search for.
        /// </param>
        /// <param name='partition'>
        /// A partition to search for.
        /// </param>
        /// <param name='owner'>
        /// An owner to search for.
        /// </param>
        /// <param name='face'>
        /// A face to search for.
        /// </param>
        /// <param name='externalId'>
        /// An external id to search for (which was associated with the video
        /// at upload).
        /// </param>
        /// <param name='pageSize'>
        /// The number of results to return.
        /// </param>
        /// <param name='skip'>
        /// The number of results to skip (used for paging).
        /// </param>
        /// <param name='sourceLanguage'>
        /// Include only videos with that source language. You can specify
        /// multiple language parameters (e.g.
        /// $language=English&amp;language=French) to search multiple
        /// languages. Having no language parameter will search all languages.
        /// Supported languages: Afrikaans: Af-ZA, Arabic: ar-EG, Bangla:
        /// Bn-BD, Bosnian: Bs-Latn, Bulgarian: Bg-BG, Catalan: Ca-ES,
        /// Chinese (Simplified): zh-Hans, Chinese (Traditional): Zh-Hant,
        /// Croatian: Hr-HR, Czech: Cs-CZ, Danish: Da-DK, Dutch: Nl-NL,
        /// English: en-US, Estonian: Et-EE, Fijian: En-FJ, Filipino: fil-PH,
        /// Finnish: Fi-FI, French: fr-FR, German: de-DE, Greek: El-GR,
        /// Haitian: Fr-HT, Hebrew: He-IL, Hindi: Hi-IN, Hungarian: Hu-HU,
        /// Indonesian: Id-ID, Italian: it-IT, Japanese: ja-JP, Kiswahili:
        /// Sw-KE, Korean: Ko-KR, Latvian: Lv-LV, Lithuanian: Lt-LT,
        /// Malagasy: Mg-MG, Malay: Ms-MY, Maltese: Mt-MT, Norwegian: Nb-NO,
        /// Persian: Fa-IR, Polish: Pl-PL, Portuguese: pt-BR, Romanian:
        /// Ro-RO, Russian: ru-RU, Samoan: En-WS, Serbian (Cyrillic):
        /// Sr-Cyrl-RS, Serbian (Latin): Sr-Latn-RS, Slovak: Sk-SK,
        /// Slovenian: Sl-SI, Spanish: es-ES, Swedish: Sv-SE, Tamil: Ta-IN,
        /// Thai: Th-TH, Tongan: To-TO, Turkish: Tr-TR, Ukrainian: Uk-UA,
        /// Urdu: Ur-PK, Vietnamese: Vi-VN. Possible values include:
        /// 'English', 'Spanish', 'Russian', 'Japanese', 'German', 'French',
        /// 'Portuguese', 'Italian', 'Chinese', 'Filipino', 'Arabic',
        /// 'ar-EG', 'en-US', 'es-ES', 'fr-FR', 'de-DE', 'it-IT', 'ja-JP',
        /// 'pt-BR', 'ru-RU', 'zh-Hans', 'fil-PH', 'Af-ZA', 'Bn-BD',
        /// 'Bs-Latn', 'Bg-BG', 'Ca-ES', 'Hr-HR', 'Cs-CZ', 'Da-DK', 'Nl-NL',
        /// 'En-FJ', 'En-WS', 'Et-EE', 'Fi-FI', 'El-GR', 'Fr-HT', 'He-IL',
        /// 'Hi-IN', 'Hu-HU', 'Id-ID', 'Sw-KE', 'Ko-KR', 'Lv-LV', 'Lt-LT',
        /// 'Mg-MG', 'Ms-MY', 'Mt-MT', 'Nb-NO', 'Fa-IR', 'Pl-PL', 'Ro-RO',
        /// 'Sr-Cyrl-RS', 'Sr-Latn-RS', 'Sk-SK', 'Sl-SI', 'Sv-SE', 'Ta-IN',
        /// 'Th-TH', 'To-TO', 'Tr-TR', 'Uk-UA', 'Ur-PK', 'Vi-VN', 'Zh-Hant'
        /// </param>
        /// <param name='language'>
        /// The language to search in. You can specify multiple language
        /// parameters (e.g. $language=English&amp;language=French) to search
        /// multiple languages. Having no language parameter will search all
        /// languages.
        /// Supported languages: Afrikaans: Af-ZA, Arabic: ar-EG, Bangla:
        /// Bn-BD, Bosnian: Bs-Latn, Bulgarian: Bg-BG, Catalan: Ca-ES,
        /// Chinese (Simplified): zh-Hans, Chinese (Traditional): Zh-Hant,
        /// Croatian: Hr-HR, Czech: Cs-CZ, Danish: Da-DK, Dutch: Nl-NL,
        /// English: en-US, Estonian: Et-EE, Fijian: En-FJ, Filipino: fil-PH,
        /// Finnish: Fi-FI, French: fr-FR, German: de-DE, Greek: El-GR,
        /// Haitian: Fr-HT, Hebrew: He-IL, Hindi: Hi-IN, Hungarian: Hu-HU,
        /// Indonesian: Id-ID, Italian: it-IT, Japanese: ja-JP, Kiswahili:
        /// Sw-KE, Korean: Ko-KR, Latvian: Lv-LV, Lithuanian: Lt-LT,
        /// Malagasy: Mg-MG, Malay: Ms-MY, Maltese: Mt-MT, Norwegian: Nb-NO,
        /// Persian: Fa-IR, Polish: Pl-PL, Portuguese: pt-BR, Romanian:
        /// Ro-RO, Russian: ru-RU, Samoan: En-WS, Serbian (Cyrillic):
        /// Sr-Cyrl-RS, Serbian (Latin): Sr-Latn-RS, Slovak: Sk-SK,
        /// Slovenian: Sl-SI, Spanish: es-ES, Swedish: Sv-SE, Tamil: Ta-IN,
        /// Thai: Th-TH, Tongan: To-TO, Turkish: Tr-TR, Ukrainian: Uk-UA,
        /// Urdu: Ur-PK, Vietnamese: Vi-VN. Possible values include:
        /// 'English', 'Spanish', 'Russian', 'Japanese', 'German', 'French',
        /// 'Portuguese', 'Italian', 'Chinese', 'Filipino', 'Arabic',
        /// 'ar-EG', 'en-US', 'es-ES', 'fr-FR', 'de-DE', 'it-IT', 'ja-JP',
        /// 'pt-BR', 'ru-RU', 'zh-Hans', 'fil-PH', 'Af-ZA', 'Bn-BD',
        /// 'Bs-Latn', 'Bg-BG', 'Ca-ES', 'Hr-HR', 'Cs-CZ', 'Da-DK', 'Nl-NL',
        /// 'En-FJ', 'En-GB', 'En-WS', 'Es-MX', 'Et-EE', 'Fi-FI', 'El-GR',
        /// 'Fr-HT', 'He-IL', 'Hi-IN', 'Hu-HU', 'Id-ID', 'Sw-KE', 'Ko-KR',
        /// 'Lv-LV', 'Lt-LT', 'Mg-MG', 'Ms-MY', 'Mt-MT', 'Nb-NO', 'Fa-IR',
        /// 'Pl-PL', 'Ro-RO', 'Sr-Cyrl-RS', 'Sr-Latn-RS', 'Sk-SK', 'Sl-SI',
        /// 'Sv-SE', 'Ta-IN', 'Th-TH', 'To-TO', 'Tr-TR', 'Uk-UA', 'Ur-PK',
        /// 'Vi-VN', 'Zh-Hant'
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos or account scope search&lt;br&gt;
        /// Access token should match the authorization scope of the call - A
        /// video token (for a single video search) or account token with
        /// read permissions&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> SearchVideosWithHttpMessagesAsync(string location, string accountId, string query = default(string), string textScope = default(string), string privacy = default(string), string id = default(string), string partition = default(string), string owner = default(string), string face = default(string), string externalId = default(string), int? pageSize = default(int?), int? skip = default(int?), string sourceLanguage = "English", string language = "English", string accessToken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Video
        /// </summary>
        /// Deletes the specified video and all related insights created from
        /// when the video was indexed
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The id of the video to delete
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Video or Account, with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteVideoWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Re-Index Video
        /// </summary>
        /// Re-index video
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='indexingPreset'>
        /// Indexing presets:
        /// NoiseReduction - Will run an additional step of noise reduction.
        /// Audio Only - get insights from audio only.
        /// Video Only - get insights from video only.
        /// Default - Use no preset (similar to not populating the parameter).
        /// Possible values include: 'Default', 'AudioOnly', 'VideoOnly',
        /// 'DefaultWithNoiseReduction'
        /// </param>
        /// <param name='streamingPreset'>
        /// Streaming presets:
        /// Default - Single layer (similar to not sending the parameter)
        /// AdaptiveBitrate - Multiple layers based on media's framerate
        /// SingleBitrate - Single layer
        /// . Possible values include: 'Default', 'AdaptiveBitrate',
        /// 'NoStreaming', 'SingleBitrate'
        /// </param>
        /// <param name='callbackUrl'>
        /// The callback uri to call with the status once the operation
        /// completes
        /// </param>
        /// <param name='sourceLanguage'>
        /// The language to set set as the source language of the video, to be
        /// used when generating the transcript. Arabic: ar-EG, Chinese
        /// (Simplified): zh-Hans, English: en-US, French: fr-FR, German:
        /// de-DE, Italian: it-IT, Japanese: ja-JP, Portuguese: pt-BR,
        /// Russian: ru-RU, Spanish: es-ES, Korean: ko-KR, Hindi: hi-IN or
        /// Auto (automatic language detection). Possible values include:
        /// 'auto', 'English', 'Spanish', 'Russian', 'Japanese', 'German',
        /// 'French', 'Portuguese', 'Italian', 'Chinese', 'Arabic', 'ar-EG',
        /// 'en-US', 'es-ES', 'ru-RU', 'ja-JP', 'de-DE', 'fr-FR', 'pt-BR',
        /// 'it-IT', 'zh-CN', 'hi-IN', 'ko-KR'
        /// </param>
        /// <param name='languageModelId'>
        /// LanguageModelId as appears in the LanguageModel returned by
        /// Language customization APIs
        /// </param>
        /// <param name='priority'>
        /// Index priority (Low, Normal and High). Can be used in paid regions
        /// only. Possible values include: 'Low', 'Normal', 'High'
        /// </param>
        /// <param name='personModelId'>
        /// Faces will be identified against the provided person model.
        /// </param>
        /// <param name='brandsCategories'>
        /// List of brands categories delimited by comma. Video indexer will
        /// only take these categories in to account when indexing. If not
        /// specified all brands will be used.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ReIndexVideoWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken, string indexingPreset = default(string), string streamingPreset = default(string), string callbackUrl = default(string), string sourceLanguage = default(string), string languageModelId = default(string), string priority = default(string), string personModelId = default(string), string brandsCategories = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update Face
        /// </summary>
        /// Update face
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='faceId'>
        /// The face id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='newName'>
        /// A name for the face
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UpdateFaceWithHttpMessagesAsync(string location, string accountId, string videoId, int faceId, string accessToken, string newName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update Transcript
        /// </summary>
        /// Updates the video with the given transcript.
        /// If the specified language is the source language of the video,
        /// then the video will be re-indexed with the given transcript, and
        /// the transcript of all the other languages will be re-generated.
        /// If the specified language is not the source language, the
        /// transcript of that language will be updated and the new text will
        /// be written into the existing lines and blocks of that language.
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='language'>
        /// The language to search in. You can specify multiple language
        /// parameters (e.g. $language=English&amp;language=French) to search
        /// multiple languages. Having no language parameter will search all
        /// languages.
        /// Supported languages: Afrikaans: Af-ZA, Arabic: ar-EG, Bangla:
        /// Bn-BD, Bosnian: Bs-Latn, Bulgarian: Bg-BG, Catalan: Ca-ES,
        /// Chinese (Simplified): zh-Hans, Chinese (Traditional): Zh-Hant,
        /// Croatian: Hr-HR, Czech: Cs-CZ, Danish: Da-DK, Dutch: Nl-NL,
        /// English: en-US, Estonian: Et-EE, Fijian: En-FJ, Filipino: fil-PH,
        /// Finnish: Fi-FI, French: fr-FR, German: de-DE, Greek: El-GR,
        /// Haitian: Fr-HT, Hebrew: He-IL, Hindi: Hi-IN, Hungarian: Hu-HU,
        /// Indonesian: Id-ID, Italian: it-IT, Japanese: ja-JP, Kiswahili:
        /// Sw-KE, Korean: Ko-KR, Latvian: Lv-LV, Lithuanian: Lt-LT,
        /// Malagasy: Mg-MG, Malay: Ms-MY, Maltese: Mt-MT, Norwegian: Nb-NO,
        /// Persian: Fa-IR, Polish: Pl-PL, Portuguese: pt-BR, Romanian:
        /// Ro-RO, Russian: ru-RU, Samoan: En-WS, Serbian (Cyrillic):
        /// Sr-Cyrl-RS, Serbian (Latin): Sr-Latn-RS, Slovak: Sk-SK,
        /// Slovenian: Sl-SI, Spanish: es-ES, Swedish: Sv-SE, Tamil: Ta-IN,
        /// Thai: Th-TH, Tongan: To-TO, Turkish: Tr-TR, Ukrainian: Uk-UA,
        /// Urdu: Ur-PK, Vietnamese: Vi-VN.
        /// </param>
        /// <param name='setAsSourceLanguage'>
        /// If true the language parameter will be set as source language.
        /// Possible values include: 'true', 'false'
        /// </param>
        /// <param name='callbackUrl'>
        /// A callback url to call with the status once the operation completes
        /// </param>
        /// <param name='vttBody'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UpdateTranscriptWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken, string language, string setAsSourceLanguage = "false", string callbackUrl = default(string), object vttBody = default(object), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Video Source File
        /// </summary>
        /// Deletes only the video source file, while keeping all insights
        /// created from when the video was indexed
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Video or Account, with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteVideoSourceFileWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Video Source File Download Url
        /// </summary>
        /// Get video source file download url
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos&lt;br&gt;
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetVideoSourceFileDownloadUrlWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Video Captions
        /// </summary>
        /// Get video captions
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos&lt;br&gt;
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='format'>
        /// The captions format (vtt, ttml, srt). Possible values include:
        /// 'vtt', 'ttml', 'srt'
        /// </param>
        /// <param name='language'>
        /// The language of the captions.
        /// Supported languages: Afrikaans: Af-ZA, Arabic: ar-EG, Bangla:
        /// Bn-BD, Bosnian: Bs-Latn, Bulgarian: Bg-BG, Catalan: Ca-ES,
        /// Chinese (Simplified): zh-Hans, Chinese (Traditional): Zh-Hant,
        /// Croatian: Hr-HR, Czech: Cs-CZ, Danish: Da-DK, Dutch: Nl-NL,
        /// English: en-US, Estonian: Et-EE, Fijian: En-FJ, Filipino: fil-PH,
        /// Finnish: Fi-FI, French: fr-FR, German: de-DE, Greek: El-GR,
        /// Haitian: Fr-HT, Hebrew: He-IL, Hindi: Hi-IN, Hungarian: Hu-HU,
        /// Indonesian: Id-ID, Italian: it-IT, Japanese: ja-JP, Kiswahili:
        /// Sw-KE, Korean: Ko-KR, Latvian: Lv-LV, Lithuanian: Lt-LT,
        /// Malagasy: Mg-MG, Malay: Ms-MY, Maltese: Mt-MT, Norwegian: Nb-NO,
        /// Persian: Fa-IR, Polish: Pl-PL, Portuguese: pt-BR, Romanian:
        /// Ro-RO, Russian: ru-RU, Samoan: En-WS, Serbian (Cyrillic):
        /// Sr-Cyrl-RS, Serbian (Latin): Sr-Latn-RS, Slovak: Sk-SK,
        /// Slovenian: Sl-SI, Spanish: es-ES, Swedish: Sv-SE, Tamil: Ta-IN,
        /// Thai: Th-TH, Tongan: To-TO, Turkish: Tr-TR, Ukrainian: Uk-UA,
        /// Urdu: Ur-PK, Vietnamese: Vi-VN. Possible values include:
        /// 'English', 'Spanish', 'Russian', 'Japanese', 'German', 'French',
        /// 'Portuguese', 'Italian', 'Chinese', 'Filipino', 'Arabic',
        /// 'ar-EG', 'en-US', 'es-ES', 'fr-FR', 'de-DE', 'it-IT', 'ja-JP',
        /// 'pt-BR', 'ru-RU', 'zh-Hans', 'fil-PH', 'Af-ZA', 'Bn-BD',
        /// 'Bs-Latn', 'Bg-BG', 'Ca-ES', 'Hr-HR', 'Cs-CZ', 'Da-DK', 'Nl-NL',
        /// 'En-FJ', 'En-GB', 'En-WS', 'Es-MX', 'Et-EE', 'Fi-FI', 'El-GR',
        /// 'Fr-HT', 'He-IL', 'Hi-IN', 'Hu-HU', 'Id-ID', 'Sw-KE', 'Ko-KR',
        /// 'Lv-LV', 'Lt-LT', 'Mg-MG', 'Ms-MY', 'Mt-MT', 'Nb-NO', 'Fa-IR',
        /// 'Pl-PL', 'Ro-RO', 'Sr-Cyrl-RS', 'Sr-Latn-RS', 'Sk-SK', 'Sl-SI',
        /// 'Sv-SE', 'Ta-IN', 'Th-TH', 'To-TO', 'Tr-TR', 'Uk-UA', 'Ur-PK',
        /// 'Vi-VN', 'Zh-Hant'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetVideoCaptionsWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken = default(string), string format = "vtt", string language = "English", Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Video Id by External Id
        /// </summary>
        /// Get video id by external id
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='externalId'>
        /// The external id
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos&lt;br&gt;
        /// Access token should match the authorization scope of the call
        /// (Account with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetVideoIdByExternalIdWithHttpMessagesAsync(string location, string accountId, string externalId, string accessToken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Thumbnail
        /// </summary>
        /// Get thumbnail of a video
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='thumbnailId'>
        /// The thumbnail id
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos&lt;br&gt;
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='format'>
        /// The thumbnail format. Possible values include: 'Jpeg', 'Base64'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetThumbnailWithHttpMessagesAsync(string location, string accountId, string videoId, string thumbnailId, string accessToken = default(string), string format = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Insights Widget
        /// </summary>
        /// Get insights widget
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// A video access token with permissions that correspond to allowEdit
        /// parameter
        /// </param>
        /// <param name='widgetType'>
        /// The type of widgets to include. Possible values include: 'People',
        /// 'Sentiments', 'Keywords', 'Search'
        /// </param>
        /// <param name='allowEdit'>
        /// Whether the widget allows editing of the insights. Possible values
        /// include: 'true', 'false'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetInsightsWidgetWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken = default(string), string widgetType = default(string), string allowEdit = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Player Widget
        /// </summary>
        /// Get player widget
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='accessToken'>
        /// A video access token with read permissions
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetPlayerWidgetWithHttpMessagesAsync(string location, string accountId, string videoId, string accessToken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Brands
        /// </summary>
        /// Gets all custom brands per the account and Bing brands activation
        /// state (whether Bing brands should be used when applying the model)
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetBrandsWithHttpMessagesAsync(string location, string accountId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create Brand
        /// </summary>
        /// Creates a new custom brand for the specified account
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the
        /// call&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='body'>
        /// A create brand request
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreateBrandWithHttpMessagesAsync(string location, string accountId, string accessToken, object body = default(object), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Brand
        /// </summary>
        /// Get specific brand
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='id'>
        /// The brand id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetBrandWithHttpMessagesAsync(string location, string accountId, int id, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update Brand
        /// </summary>
        /// Update Brand
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='id'>
        /// The brand id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='body'>
        /// The updated brand
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UpdateBrandWithHttpMessagesAsync(string location, string accountId, int id, string accessToken, object body = default(object), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Brand
        /// </summary>
        /// Removes a brand in the specified account
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='id'>
        /// The brand id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account and Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteBrandWithHttpMessagesAsync(string location, string accountId, int id, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Brands Model Settings
        /// </summary>
        /// Gets the model settings which determines which brands to use
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetBrandsModelSettingsWithHttpMessagesAsync(string location, string accountId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update Brands Model Settings
        /// </summary>
        /// Update the brand model settings
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='body'>
        /// The updated brand model settings
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UpdateBrandsModelSettingsWithHttpMessagesAsync(string location, string accountId, string accessToken, object body = default(object), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create Language Model
        /// </summary>
        /// Creates a language model.
        /// There are two ways to upload files in the body using form-data.
        /// 1. Key will be the file name and value will be the file.
        /// 2. Key will be the file name and value will be a URL to txt file.
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account and Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelName'>
        /// Model name
        /// </param>
        /// <param name='language'>
        /// Model language. Possible values include: 'en-US', 'ar-EG',
        /// 'de-DE', 'es-ES', 'fr-FR', 'hi-HI', 'it-IT', 'ja-JP', 'pt-BR',
        /// 'ru-RU', 'zh-CN'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreateLanguageModelWithHttpMessagesAsync(string location, string accountId, string accessToken, string modelName, string language, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Language Models
        /// </summary>
        /// Get language models
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebFourNineSevenNineeSixecbdThreeZerofaaSixfSevenFiveWithHttpMessagesAsync(string location, string accountId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update Language Model
        /// </summary>
        /// Updates a language model.
        /// 
        /// There are two ways to upload files in the body using form-data.
        /// 1. Key will be the file name and value will be the file.
        /// 2. Key will be the file name and value will be a URL to txt file.
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelName'>
        /// Model name
        /// </param>
        /// <param name='enable'>
        /// Enable / Disable all files under the model. Possible values
        /// include: 'true', 'false'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebThreeceEightFivefFourSixEightFourTwoFourZerobdbSevenEightfWithHttpMessagesAsync(string location, string accountId, string modelId, string accessToken, string modelName = default(string), string enable = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Language Model
        /// </summary>
        /// Get language model
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebFourfcbdNinebFourThreeSevendTwoSevendFiveThreefOneSixWithHttpMessagesAsync(string location, string accountId, string modelId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Language Model
        /// </summary>
        /// Delete language model
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account and Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebaFiveThreeSevenEightTwoSixZeroSixeNineOnefSixFivebeNinedWithHttpMessagesAsync(string location, string accountId, string modelId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Language Model file
        /// </summary>
        /// Delete language model file
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='fileId'>
        /// File id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account and Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebFiveSevenbFivedeFiveOneeSixFoureeFiveTwoTwoFourTwoeWithHttpMessagesAsync(string location, string accountId, string modelId, string fileId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update Language Model file
        /// </summary>
        /// Update a language model file name or state
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='fileId'>
        /// File id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='fileName'>
        /// File name
        /// </param>
        /// <param name='enable'>
        /// Enable. Possible values include: 'true', 'false'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebSixZeroFiveFourSevenfThreeThreecOnecTwobTwodOneThreeSevenFiveWithHttpMessagesAsync(string location, string accountId, string modelId, string fileId, string accessToken, string fileName = default(string), string enable = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Language Model file data
        /// </summary>
        /// Get language model file data and metadata
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='fileId'>
        /// File id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebSevenThreefNineeSixFourOneSixdSevenaNineNineSixFivebFourTwoWithHttpMessagesAsync(string location, string accountId, string modelId, string fileId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Download Language Model file content
        /// </summary>
        /// Downlaod language model file content
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='fileId'>
        /// File id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebNineNineeFiveTwoTwocbFourSevenbdNineSixSevenNineOneTwoTwoWithHttpMessagesAsync(string location, string accountId, string modelId, string fileId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Train Language Model
        /// </summary>
        /// Train the language model based on the enabled files
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;
        /// . Possible values include: 'northeurope', 'westus2', 'eastasia',
        /// 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='modelId'>
        /// Model id
        /// </param>
        /// <param name='accessToken'>
        /// Access token should match the authorization scope of the call
        /// (Account, with Write)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> FiveaeFivebacThreecfSevenSixOneSevenSevenNineaSixcTwoabTwoSevenWithHttpMessagesAsync(string location, string accountId, string modelId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Video Artifact Download Url
        /// </summary>
        /// Get video artifact download url
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'northeurope', 'westus2', 'eastasia', 'trial'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='videoId'>
        /// The video id
        /// </param>
        /// <param name='type'>
        /// The artifact type to get. Possible values include: 'Ocr', 'Faces',
        /// 'FacesThumbnails', 'VisualContentModeration',
        /// 'KeyframesThumbnails', 'LanguageDetection', 'Metadata',
        /// 'Emotions', 'TextualContentModeration'
        /// </param>
        /// <param name='accessToken'>
        /// Required for private videos&lt;br&gt;
        /// Access token should match the authorization scope of the call
        /// (Account or Video, with Read)&lt;br&gt;
        /// Note that Access tokens expire within 1 hour&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetVideoArtifactDownloadUrlWithHttpMessagesAsync(string location, string accountId, string videoId, string type, string accessToken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create Person Model
        /// </summary>
        /// Creates a new person model in the specified account.
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'trial', 'northeurope', 'eastasia', 'westus2'
        /// </param>
        /// <param name='accountId'>
        /// Format - uuid. Account ID is a globally unique identifier (GUID)
        /// for the account.&lt;br&gt; See more details &lt;a
        /// href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='name'>
        /// The person model name.
        /// </param>
        /// <param name='accessToken'>
        /// An account access token with write permissions.&lt;br&gt;Note that
        /// Access tokens expire within 1 hour.&lt;br&gt;See more details
        /// &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreatePersonModelWithHttpMessagesAsync(string location, string accountId, string name, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Person Models
        /// </summary>
        /// Gets all person models in the account.
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'trial', 'northeurope', 'eastasia', 'westus2'
        /// </param>
        /// <param name='accountId'>
        /// Format - uuid. Account ID is a globally unique identifier (GUID)
        /// for the account.&lt;br&gt; See more details &lt;a
        /// href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='accessToken'>
        /// An account access token with read permissions.&lt;br&gt;Note that
        /// Access tokens expire within 1 hour.&lt;br&gt;See more details
        /// &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> GetPersonModelsWithHttpMessagesAsync(string location, string accountId, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Person Model
        /// </summary>
        /// Deletes the given person model.
        /// <param name='location'>
        /// Location indicates the Azure region to which the call should be
        /// routed&lt;br&gt;See more details &lt;a
        /// href=https://aka.ms/vi-docs-location
        /// target="_blank"&gt;here&lt;/a&gt;. Possible values include:
        /// 'trial', 'northeurope', 'eastasia', 'westus2'
        /// </param>
        /// <param name='accountId'>
        /// Account ID is a globally unique identifier (GUID) for the
        /// account&lt;br&gt;
        /// See more details &lt;a href=https://aka.ms/vi-docs-accountid
        /// target="_blank"&gt;here&lt;/a&gt;
        /// </param>
        /// <param name='id'>
        /// The person model id
        /// </param>
        /// <param name='accessToken'>
        /// An account access token with write permissions.&lt;br&gt;Note that
        /// Access tokens expire within 1 hour.&lt;br&gt;See more details
        /// &lt;a href=https://aka.ms/vi-docs-accesstoken
        /// target="_blank"&gt;here&lt;/a&gt;.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeletePersonModelWithHttpMessagesAsync(string location, string accountId, string id, string accessToken, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
